export const StateConstants = {
  player: {
    STANDING_LEFT: 'STANDING_LEFT',
    STANDING_RIGHT: 'STANDING_RIGHT',
    IS_GROUNDED: 'IS_GROUNDED',
    RUNNING_LEFT: 'RUNNING_LEFT',
    RUNNING_RIGHT: 'RUNNING_RIGHT'
  }
}
