export const StateConstants = {
  player: {
    STANDING_LEFT: 'STANDING_LEFT',
    STANDING_RIGHT: 'STANDING_RIGHT',
    JUMPING: 'JUMPING',
    FALLING: 'FALLING',
    RUNNING_LEFT: 'RUNNING_LEFT',
    RUNNING_RIGHT: 'RUNNING_RIGHT'
  }
}
